name: inf-conda-env
channels:
  - defaults
dependencies:
  - python=3.9  # or the version of Python you're using
  - pip
  - pip:
      - tensorflow #same as for training the model
      - numpy
      - azureml-defaults
      - azureml-inference-server-http  # Ensure this package is included
      - azureml-dataprep
      - azureml-dataprep-native
      - azureml-dataset-runtime
      - inference-schema[numpy-support]
      
      
