$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: mnist-deployment-v1
endpoint_name: myendpoint-ville

model:
  path: ./app # Path to your model files
  name: my_model.keras
  #version: 4

code_configuration:
  code: ./app # Path to your code directory
  scoring_script: score.py # Your entry script for scoring

environment: azureml:my-custom-env:6 # Specify the environment registered in Azure ML

instance_type: Standard_D2as_v4
instance_count: 1
